added bookmark page and bookmark service
vmeet24/Team-2-Frontend pull request #4
Opened 2022-11-27 20:27 UTC by Abdulzy

2022-11-28 00:34 UTC, gurishe commented
This looks good. I might have expected a few smaller commits rather than 1 larger commit, but the number of lines added is not too much.

That said, we should also get some tests added for both the bookmarks service API and maybe even the bookmarks page. Perhaps we can add those two as a separate ticket for this coming sprint though. I think this is good to merge as is and we'll make sure to get the testing tickets added.

2022-11-28 18:56 UTC, prinjal requested changes
Can we correct the deployment errors, please?

2022-11-29 15:59 UTC, prinjal approved these changes

2022-11-29 15:59 UTC, prinjal commented
> Can we correct the deployment errors, please?

Looks good to me. Thanks @Abdulzy

2022-11-29 16:31 UTC, merged